name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: mssql-cli-windows.exe
            path_sep: ";"
          - os: ubuntu-latest
            artifact_name: mssql-cli-linux
            path_sep: ":"

    steps:
      - uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          uv pip install .
          uv pip install pyinstaller requests future

      - name: Download binaries
        run: uv run dev_setup.py

      - name: PyInstaller Build
        shell: bash
        run: |
          uv run pyinstaller --onefile --name "${{ matrix.artifact_name }}" \
          --collect-all "mssqlcli" \
          --add-data "mssqlcli/mssqltoolsservice/bin${{ matrix.path_sep }}mssqlcli/mssqltoolsservice/bin" \
          --add-data "mssqlcli/packages/mssqlliterals/*.json${{ matrix.path_sep }}mssqlcli/packages/mssqlliterals" \
          --hidden-import "pyodbc" \
          mssqlcli/main.py

      # --- MAC OS TEST ---
      - name: Validate Binary Execution (${{ matrix.os }})
        shell: bash
        run: |
          # Define executable path
          EXE_PATH="dist/${{ matrix.artifact_name }}"
          
          # Exec permission
          chmod +x "$EXE_PATH"
          
          # Test executable
          echo "Testing binary version and engine initialization..."
          "$EXE_PATH" --version
          
          # Binary OK
          echo "Binary validation successful on ${{ matrix.os }}!"
      # --- MAC OS TEST ---
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/${{ matrix.artifact_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}